id: IA3FF4F88
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:24:13.782029
last_modified: 2023-02-08 15:24:13.782183
source_metadata:
  title: Sarvadharmāpravṛttinirdeśa
  language: zh
bases:
  E05B:
    base_file: E05B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
